# Generated by Django 5.2.9 on 2026-02-14 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('hires', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('status', models.CharField(choices=[('pending', 'ожидает оплаты'), ('succeeded', 'оплачено'), ('failed', 'не удалось'), ('cancelled', 'отменён'), ('refunded', 'возвращён')], db_index=True, default='pending', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='оплачен')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.booking', verbose_name='бронирование')),
                ('hire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hires.hire', verbose_name='найм специалиста')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.renter', verbose_name='плательщик')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
