# Generated by Django 5.2.9 on 2026-03-15 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.renter', verbose_name='организатор'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date', 'status'], name='events_even_date_9259aa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['renter'], name='events_even_renter__2c91b2_idx'),
        ),
    ]
