# Generated by Django 5.2.9 on 2026-02-14 16:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='название площадки')),
                ('slug', models.SlugField(help_text='для URL, например: loft-na-pokrovke', max_length=250, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='короткое описание')),
                ('address', models.CharField(max_length=300, verbose_name='адрес')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='город')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='почтовый индекс')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='долгота')),
                ('capacity_min', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='минимальная вместимость')),
                ('capacity_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='максимальная вместимость')),
                ('area_sq_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='площадь, м²')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена за час')),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена за сутки')),
                ('min_booking_hours', models.PositiveSmallIntegerField(default=2, verbose_name='минимальное бронирование, часов')),
                ('cancellation_policy', models.TextField(blank=True, help_text='например: бесплатная отмена за 48 часов', verbose_name='политика отмены')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('published', 'опубликовано'), ('archived', 'в архиве'), ('moderation', 'на модерации')], db_index=True, default='draft', max_length=20, verbose_name='статус')),
                ('is_verified', models.BooleanField(default=False, verbose_name='проверена администратором')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='users.owner', verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'площадка',
                'verbose_name_plural': 'площадки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/%Y/%m/', verbose_name='фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city', 'status'], name='venues_venu_city_085ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['owner'], name='venues_venu_owner_i_eef73e_idx'),
        ),
    ]
