# Generated by Django 5.2.9 on 2026-02-14 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='доступ в админку')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН / ЕГРН')),
                ('verified', models.BooleanField(default=False, verbose_name='проверен')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='рейтинг')),
            ],
            options={
                'verbose_name': 'владелец',
                'verbose_name_plural': 'владельцы',
            },
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='renter', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'арендатор',
                'verbose_name_plural': 'арендаторы',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='specialist', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('specialty', models.CharField(blank=True, max_length=150, verbose_name='специализация')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='номер лицензии')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='город работы')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='рейтинг')),
            ],
            options={
                'verbose_name': 'специалист',
                'verbose_name_plural': 'специалисты',
            },
        ),
    ]
