# Generated by Django 5.2.9 on 2026-03-15 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='начало работы')),
                ('end_datetime', models.DateTimeField(verbose_name='окончание работы')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='итоговая стоимость услуг')),
                ('status', models.CharField(choices=[('pending', 'ожидает подтверждения'), ('confirmed', 'подтверждено'), ('cancelled', 'отменено'), ('completed', 'выполнено')], db_index=True, default='pending', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hires', to='events.event', verbose_name='заказчик / организатор')),
            ],
            options={
                'verbose_name': 'найм специалиста',
                'verbose_name_plural': 'наймы специалистов',
                'ordering': ['-created_at'],
            },
        ),
    ]
