# Generated by Django 5.2.9 on 2026-02-14 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='название мероприятия')),
                ('date', models.DateField(verbose_name='дата проведения')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='время окончания')),
                ('theme', models.CharField(choices=[('party', 'вечеринка / день рождения'), ('wedding', 'свадьба'), ('corporate', 'корпоратив / тимбилдинг'), ('conference', 'конференция / семинар'), ('workshop', 'мастер-класс / тренинг'), ('photo_session', 'фотосессия / съёмка'), ('concert', 'концерт / выступление'), ('private', 'закрытое мероприятие'), ('other', 'другое')], default='other', max_length=40, verbose_name='тематика / формат')),
                ('short_description', models.CharField(blank=True, help_text='до 300 символов, отображается в списке', max_length=300, verbose_name='короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='подробное описание')),
                ('expected_guests', models.PositiveSmallIntegerField(default=20, help_text='примерное число участников', verbose_name='ожидаемое количество гостей')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('planned', 'запланировано'), ('active', 'идёт подготовка'), ('ongoing', 'проходит сейчас'), ('completed', 'завершено'), ('cancelled', 'отменено')], db_index=True, default='draft', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.renter', verbose_name='организатор')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'status'], name='events_even_date_9259aa_idx'), models.Index(fields=['renter'], name='events_even_renter__2c91b2_idx')],
            },
        ),
    ]
