# Generated by Django 5.2.9 on 2026-03-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('events', '0002_initial'),
        ('hires', '0003_alter_hire_event'),
        ('users', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='specialists',
            field=models.ManyToManyField(related_name='events', through='hires.Hire', through_fields=('event', 'specialist'), to='users.specialist'),
        ),
        migrations.AddField(
            model_name='event',
            name='venues',
            field=models.ManyToManyField(related_name='events', through='bookings.Booking', through_fields=('event', 'venue'), to='venues.venue'),
        ),
    ]
