version: '3.9'

services:
  db:
    image: postgres:18
    container_name: eventmarket_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: EventMarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: