# Generated by Django 5.2.9 on 2026-02-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='начало работы')),
                ('end_datetime', models.DateTimeField(verbose_name='окончание работы')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='итоговая стоимость услуг')),
                ('status', models.CharField(choices=[('pending', 'ожидает подтверждения'), ('confirmed', 'подтверждено'), ('cancelled', 'отменено'), ('completed', 'выполнено')], db_index=True, default='pending', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='events.event', verbose_name='мероприятие')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hires', to='users.renter', verbose_name='заказчик / организатор')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hires', to='users.specialist', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'найм специалиста',
                'verbose_name_plural': 'наймы специалистов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='hires_hire_status_8f0d3d_idx'), models.Index(fields=['event', 'specialist'], name='hires_hire_event_i_8a6418_idx')],
            },
        ),
    ]
