# Generated by Django 5.2.9 on 2026-03-15 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hires', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hires', to='users.specialist', verbose_name='специалист'),
        ),
        migrations.AddIndex(
            model_name='hire',
            index=models.Index(fields=['status'], name='hires_hire_status_8f0d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='hire',
            index=models.Index(fields=['event', 'specialist'], name='hires_hire_event_i_8a6418_idx'),
        ),
    ]
