# Generated by Django 5.2.9 on 2026-03-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('hires', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='events.event', verbose_name='мероприятие'),
        ),
    ]
