# Generated by Django 5.2.15 on 2026-06-12 12:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_userimage'),
        ('venues', '0002_alter_venueimage_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_reviews', to='users.renter', verbose_name='арендатор')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.specialist', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'отзыв о специалисте',
                'verbose_name_plural': 'отзывы о специалистах',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('specialist', 'renter'), name='unique_specialist_review_per_renter')],
            },
        ),
        migrations.CreateModel(
            name='VenueReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_reviews', to='users.renter', verbose_name='арендатор')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='venues.venue', verbose_name='площадка')),
            ],
            options={
                'verbose_name': 'отзыв о площадке',
                'verbose_name_plural': 'отзывы о площадках',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'renter'), name='unique_venue_review_per_renter')],
            },
        ),
    ]
