# Generated by Django 5.2.15 on 2026-06-15 17:34

from django.db import migrations, models


def approve_existing_reviews(apps, schema_editor):
    """Уже существовавшие отзывы считаем опубликованными (модерация — только для новых)."""
    apps.get_model('reviews', 'VenueReview').objects.update(status='approved')
    apps.get_model('reviews', 'SpecialistReview').objects.update(status='approved')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistreview',
            name='status',
            field=models.CharField(choices=[('pending', 'на проверке'), ('approved', 'опубликован'), ('rejected', 'отклонён')], db_index=True, default='pending', max_length=20, verbose_name='статус модерации'),
        ),
        migrations.AddField(
            model_name='venuereview',
            name='status',
            field=models.CharField(choices=[('pending', 'на проверке'), ('approved', 'опубликован'), ('rejected', 'отклонён')], db_index=True, default='pending', max_length=20, verbose_name='статус модерации'),
        ),
        migrations.RunPython(approve_existing_reviews, noop),
    ]
