# Generated by Django 5.2.9 on 2026-02-14 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='начало')),
                ('end_datetime', models.DateTimeField(verbose_name='окончание')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='итоговая стоимость')),
                ('status', models.CharField(choices=[('pending', 'ожидает подтверждения'), ('confirmed', 'подтверждено'), ('cancelled', 'отменено'), ('completed', 'завершено')], db_index=True, default='pending', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
