# Generated by Django 5.2.9 on 2026-03-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_baseuser_first_name_alter_baseuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='ссылка на портфолио'),
        ),
    ]
