# Generated by Django 5.2.9 on 2026-04-26 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_specialist_portfolio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='avatar', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('image', models.ImageField(upload_to='users/%Y/%m/', verbose_name='фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'аватар пользователя',
                'verbose_name_plural': 'аватары пользователей',
            },
        ),
    ]
