# Generated by Django 5.2.15 on 2026-06-15 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_admin_to_superusers(apps, schema_editor):
    """Выдаём роль Администратора всем существующим суперпользователям."""
    BaseUser = apps.get_model('users', 'BaseUser')
    Admin = apps.get_model('users', 'Admin')
    for user in BaseUser.objects.filter(is_superuser=True):
        Admin.objects.get_or_create(user=user)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='назначен')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_admins', to=settings.AUTH_USER_MODEL, verbose_name='кем назначен')),
            ],
            options={
                'verbose_name': 'администратор',
                'verbose_name_plural': 'администраторы',
            },
        ),
        migrations.RunPython(grant_admin_to_superusers, noop),
    ]
